baseURL = "https://famille-chauviteau.fr"
languageCode = "fr-FR"
title = "Histoire de la famille Chauviteau"
theme = "mybook"

canonifyurls = true
enableGitInfo = true
publishDir = "docs"
disableKinds = ['taxonomy', 'taxonomyTerm']

# Book configuration
disablePathToLower = true

[params]
# show or hide table of contents for page
BookShowToC = false

# Set bundle to render side menu
# if not specified file structure and weights will be used
#BookMenuBundle = "/menu"

# specify section of content to render as menu
# if bookMenuBundle is not set, 'docs' is value by default
# BookSection = ""

# BookSourceURL = 'https://github.com/LGD-Fr/famille-chauviteau.site/blob/master/content/'
BookGitURL = 'https://github.com/LGD-Fr/famille-chauviteau.fr'

ContactEMailFile = "/img/courriel.png"
ContactEMailAlt = "« contact » AROBASE « famille » TRAIT D’UNION « chauviteau » POINT « fr »"
RedirectToCanonical = false
CanonicalBaseURL = "https://famille-chauviteau.fr"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true